[settings]
experimental = true
python.uv_venv_auto = "create|source"

[prepare.uv]
auto = true

[tools]
uv = "0.10.4"

[tasks.lint]
run = "uv run ruff check"

[tasks."lint:fix"]
run = "uv run ruff check --fix"

[tasks."format"]
run = "uv run ruff format"

[tasks."format:check"]
run = "uv run ruff format --check"

[tasks.typecheck]
run = "uv run basedpyright"

[tasks.check]
depends = ["lint", "format:check", "typecheck"]

[tasks."check:fix"]
depends = ["lint:fix", "format", "typecheck"]
